CREATE TABLE IF NOT EXISTS Customer (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    address VARCHAR(250) NOT NULL,
    contact VARCHAR(20) NOT NULL
);

ALTER TABLE Customer ADD CONSTRAINT uk_contact UNIQUE (contact);

CREATE TABLE IF NOT EXISTS Item (
    code VARCHAR(50) PRIMARY KEY,
    description VARCHAR(250) NOT NULL,
    qty INT NOT NULL,
    unit_price DECIMAL(10,2) NOT NULL
);

DROP TABLE IF EXISTS Item;